/* Automatically generated file, do not edit */
#define	EDITED_ED_ARGUMENT_DIGIT      	  0
#define	EDITED_ED_CLEAR_SCREEN        	  1
#define	EDITED_ED_COMMAND             	  2
#define	EDITED_ED_DELETE_NEXT_CHAR    	  3
#define	EDITED_ED_DELETE_PREV_CHAR    	  4
#define	EDITED_ED_DELETE_PREV_WORD    	  5
#define	EDITED_ED_DIGIT               	  6
#define	EDITED_ED_END_OF_FILE         	  7
#define	EDITED_ED_IGNORE              	  8
#define	EDITED_ED_INSERT              	  9
#define	EDITED_ED_KILL_LINE           	 10
#define	EDITED_ED_MOVE_TO_BEG         	 11
#define	EDITED_ED_MOVE_TO_END         	 12
#define	EDITED_ED_NEWLINE             	 13
#define	EDITED_ED_NEXT_CHAR           	 14
#define	EDITED_ED_NEXT_HISTORY        	 15
#define	EDITED_ED_NEXT_LINE           	 16
#define	EDITED_ED_PREV_CHAR           	 17
#define	EDITED_ED_PREV_HISTORY        	 18
#define	EDITED_ED_PREV_LINE           	 19
#define	EDITED_ED_PREV_WORD           	 20
#define	EDITED_ED_QUOTED_INSERT       	 21
#define	EDITED_ED_REDISPLAY           	 22
#define	EDITED_ED_SEARCH_NEXT_HISTORY 	 23
#define	EDITED_ED_SEARCH_PREV_HISTORY 	 24
#define	EDITED_ED_SEQUENCE_LEAD_IN    	 25
#define	EDITED_ED_START_OVER          	 26
#define	EDITED_ED_TRANSPOSE_CHARS     	 27
#define	EDITED_ED_UNASSIGNED          	 28
#define	EDITED_EM_CAPITOL_CASE        	 29
#define	EDITED_EM_COPY_PREV_WORD      	 30
#define	EDITED_EM_COPY_REGION         	 31
#define	EDITED_EM_DELETE_NEXT_WORD    	 32
#define	EDITED_EM_DELETE_OR_LIST      	 33
#define	EDITED_EM_DELETE_PREV_CHAR    	 34
#define	EDITED_EM_EXCHANGE_MARK       	 35
#define	EDITED_EM_GOSMACS_TRANSPOSE   	 36
#define	EDITED_EM_INC_SEARCH_NEXT     	 37
#define	EDITED_EM_INC_SEARCH_PREV     	 38
#define	EDITED_EM_KILL_LINE           	 39
#define	EDITED_EM_KILL_REGION         	 40
#define	EDITED_EM_LOWER_CASE          	 41
#define	EDITED_EM_META_NEXT           	 42
#define	EDITED_EM_NEXT_WORD           	 43
#define	EDITED_EM_SET_MARK            	 44
#define	EDITED_EM_TOGGLE_OVERWRITE    	 45
#define	EDITED_EM_UNIVERSAL_ARGUMENT  	 46
#define	EDITED_EM_UPPER_CASE          	 47
#define	EDITED_EM_YANK                	 48
#define	EDITED_VI_ADD                 	 49
#define	EDITED_VI_ADD_AT_EOL          	 50
#define	EDITED_VI_ALIAS               	 51
#define	EDITED_VI_CHANGE_CASE         	 52
#define	EDITED_VI_CHANGE_META         	 53
#define	EDITED_VI_CHANGE_TO_EOL       	 54
#define	EDITED_VI_COMMAND_MODE        	 55
#define	EDITED_VI_COMMENT_OUT         	 56
#define	EDITED_VI_DELETE_META         	 57
#define	EDITED_VI_DELETE_PREV_CHAR    	 58
#define	EDITED_VI_END_BIG_WORD        	 59
#define	EDITED_VI_END_WORD            	 60
#define	EDITED_VI_HISTEDIT            	 61
#define	EDITED_VI_HISTORY_WORD        	 62
#define	EDITED_VI_INSERT              	 63
#define	EDITED_VI_INSERT_AT_BOL       	 64
#define	EDITED_VI_KILL_LINE_PREV      	 65
#define	EDITED_VI_LIST_OR_EOF         	 66
#define	EDITED_VI_MATCH               	 67
#define	EDITED_VI_NEXT_BIG_WORD       	 68
#define	EDITED_VI_NEXT_CHAR           	 69
#define	EDITED_VI_NEXT_WORD           	 70
#define	EDITED_VI_PASTE_NEXT          	 71
#define	EDITED_VI_PASTE_PREV          	 72
#define	EDITED_VI_PREV_BIG_WORD       	 73
#define	EDITED_VI_PREV_CHAR           	 74
#define	EDITED_VI_PREV_WORD           	 75
#define	EDITED_VI_REDO                	 76
#define	EDITED_VI_REPEAT_NEXT_CHAR    	 77
#define	EDITED_VI_REPEAT_PREV_CHAR    	 78
#define	EDITED_VI_REPEAT_SEARCH_NEXT  	 79
#define	EDITED_VI_REPEAT_SEARCH_PREV  	 80
#define	EDITED_VI_REPLACE_CHAR        	 81
#define	EDITED_VI_REPLACE_MODE        	 82
#define	EDITED_VI_SEARCH_NEXT         	 83
#define	EDITED_VI_SEARCH_PREV         	 84
#define	EDITED_VI_SUBSTITUTE_CHAR     	 85
#define	EDITED_VI_SUBSTITUTE_LINE     	 86
#define	EDITED_VI_TO_COLUMN           	 87
#define	EDITED_VI_TO_HISTORY_LINE     	 88
#define	EDITED_VI_TO_NEXT_CHAR        	 89
#define	EDITED_VI_TO_PREV_CHAR        	 90
#define	EDITED_VI_UNDO                	 91
#define	EDITED_VI_UNDO_LINE           	 92
#define	EDITED_VI_YANK                	 93
#define	EDITED_VI_YANK_END            	 94
#define	EDITED_VI_ZERO                	 95
#define	EL_NUM_FCNS                   	 96
